In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('ecommerce revenue data.csv')

In [4]:
# Quick look
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620000 entries, 0 to 619999
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          620000 non-null  object
 1   order_date        607737 non-null  object
 2   customer_id       620000 non-null  object
 3   customer_name     620000 non-null  object
 4   customer_segment  595408 non-null  object
 5   product_id        620000 non-null  object
 6   product_name      620000 non-null  object
 7   category          620000 non-null  object
 8   unit_price        607937 non-null  object
 9   cost_price        620000 non-null  float64
 10  quantity          615868 non-null  float64
 11  discount_code     620000 non-null  object
 12  discount_pct      595158 non-null  float64
 13  shipping_cost     601427 non-null  float64
 14  shipping_method   595166 non-null  object
 15  region            620000 non-null  object
 16  channel           620000 non-null  object
 17  payment_method    595225 non-null  object
 18  order_status      620000 non-null  object
 19  delivery_days     594935 non-null  float64
 20  is_returned       620000 non-null  object
 21  return_reason     55999 non-null   object
 22  customer_rating   585011 non-null  float64
 23  revenue           601539 non-null  float64
 24  profit            601381 non-null  float64
dtypes: float64(8), object(17)
memory usage: 118.3+ MB

,cost_price,quantity,discount_pct,shipping_cost,delivery_days,customer_rating,revenue,profit
count,620000.000000,615868.000000,595158.000000,601427.000000,594935.000000,585011.000000,601539.000000,601381.000000
mean,31.853390,2.421902,8.743191,13.768601,7.496071,4.066959,211.045251,117.762160
std,22.956705,1.931823,9.602908,6.492225,4.032321,1.075177,225.606178,136.716884
min,5.000000,-1.000000,0.000000,2.500000,1.000000,0.000000,17.500000,-1549.900000
25%,12.000000,1.000000,0.000000,8.150000,4.000000,4.000000,81.090000,41.490000
50%,25.000000,2.000000,0.000000,13.790000,7.000000,4.000000,137.680000,74.990000
75%,45.000000,3.000000,15.000000,19.390000,11.000000,5.000000,252.630000,145.500000
max,95.000000,10.000000,25.000000,25.000000,14.000000,6.000000,2524.870000,1549.900000

In [5]:
df

,order_id,order_date,customer_id,customer_name,customer_segment,product_id,product_name,category,unit_price,cost_price,...,region,channel,payment_method,order_status,delivery_days,is_returned,return_reason,customer_rating,revenue,profit
0,ORD-100001,08-02-2024,CUST-10144,Amara Davis,Regular,P008,Desk Lamp,Home Office,34.99,10.0,...,South,In-Store,Bank Transfer,Returned,13.0,1,Defective,5.0,72.63,49.98
1,ORD-100002,2024-03-28 06:45:00,CUST-15935,Fatima Okafor,Loyal,P012,Sneakers,Footwear,110.0,45.0,...,Central,In-Store,Credit Card,Completed,5.0,0,NaN,5.0,288.51,145.50
2,ORD-100003,10-13-2021,CUST-29077,Blessing Brown,Premium,P003,Yoga Mat,Sports,39.99,12.0,...,North,Social Media,PayPal,Completed,12.0,0,NaN,3.0,144.88,83.97
3,ORD-100004,10/11/2021,CUST-35757,james ibrahim,New,P010,Sunglasses,Accessories,89.99,30.0,...,Central,Mobile App,Debit Card,Completed,6.0,0,NaN,3.0,242.66,139.47
4,ORD-100005,2024-07-16 01:14:00,CUST-22654,Amara Davis,Premium,P019,Perfume,Beauty,79.99,22.0,...,East,Online,Debit Card,Completed,8.0,0,NaN,5.0,93.00,57.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619995,ORD-719996,04-20-2021,CUST-41395,Sarah Adeyemi,Loyal,P010,Sunglasses,Accessories,89.99,30.0,...,EAST,Mobile App,Cash on Delivery,Completed,11.0,0,NaN,3.0,180.83,101.98
619996,ORD-719997,06/07/2023,CUST-18855,Michael Davis,Premium,P006,Bluetooth Speaker,Electronics,59.99,22.0,...,north,Marketplace,PayPal,Cancelled,3.0,0,NaN,6.0,67.58,37.99
619997,ORD-719998,12-28-2024,CUST-06994,Sarah Adeyemi,New,P020,Mechanical Keyboard,Electronics,149.99,55.0,...,South,Mobile App,Bank Transfer,Completed,5.0,0,NaN,NaN,140.13,64.99
619998,ORD-719999,2022/02/19,CUST-47816,DAVID IBRAHIM,Loyal,P015,Gaming Mouse,Electronics,69.99,25.0,...,West,Marketplace,PayPal,Completed,10.0,0,NaN,4.0,77.44,27.49
619999,ORD-720000,04-17-2024,CUST-39462,FATIMA DAVIS,Premium,P009,Water Bottle,Sports,24.99,6.0,...,East,In-Store,Debit Card,Completed,1.0,0,NaN,4.0,84.39,56.97

DATA CLEANING

In [6]:
# CLEAN COLUMN NAMES
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [8]:
# CLEAN TEXT COLUMNS
text_cols = ['customer_name', 'product_name', 'channel', 'region', 'order_status']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

In [11]:
# FIX DATE COLUMN
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [12]:
# CLEAN NUMERIC COLUMNS (REMOVE $, N/A)
num_cols = ['unit_price', 'shipping_cost']

for col in num_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace('$', '', regex=False)
        .str.replace(',', '', regex=False)
        .replace('N/A', np.nan)
    )
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [13]:
# FIX QUANTITY (REMOVE INVALID VALUES)
df = df[df['quantity'] > 0]

In [14]:
# FIX BOOLEAN COLUMN 
df['is_returned'] = df['is_returned'].astype(str).str.lower().map({
    'yes': 1, 'true': 1, '1': 1,
    'no': 0, 'false': 0, '0': 0
})

C:\Users\PC\AppData\Local\Temp\ipykernel_3408\3662127207.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_returned'] = df['is_returned'].astype(str).str.lower().map({

In [17]:
# FILLING MISSING VALUES
df['customer_segment'].fillna('unknown', inplace=True)
df['shipping_method'].fillna('unknown', inplace=True)
df['payment_method'].fillna('unknown', inplace=True)

C:\Users\PC\AppData\Local\Temp\ipykernel_3408\3030502373.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_segment'].fillna('unknown', inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_3408\3030502373.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['shipping_method'].fillna('unknown', inplace=True)
C:\Users\PC\AppData\Local\Temp\ipykernel_3408\3030502373.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['payment_method'].fillna('unknown', inplace=True)

In [ ]:
# FIXING DISCOUNT COLUMN
df['discount_pct'] = df['discount_pct'].fillna(0)

C:\Users\PC\AppData\Local\Temp\ipykernel_3408\3891366467.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['discount_pct'] = df['discount_pct'].fillna(0)

In [19]:
# FILTERING CUSTOMER RATING
df = df[(df['customer_rating'] >= 1) & (df['customer_rating'] <= 5)]

In [ ]:
# RE-CALCULATING REVENUE 
df.loc[df['discount_pct'] > 1, 'discount_pct'] = df['discount_pct'] / 100
df['revenue_clean'] = df['unit_price'] * df['quantity'] * (1 - df['discount_pct'])

C:\Users\PC\AppData\Local\Temp\ipykernel_3408\4065360979.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['revenue_clean'] = df['unit_price'] * df['quantity'] * (1 - df['discount_pct'])

In [23]:
#RE-CALCULATING THE PROFIT
df['profit_clean'] = (
    df['revenue_clean']
    - (df['cost_price'] * df['quantity'])
    - df['shipping_cost']
)

C:\Users\PC\AppData\Local\Temp\ipykernel_3408\42523726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['profit_clean'] = (

In [25]:
df.to_csv('cleaned_ecommerce_data.csv', index=False)